# Generated by Django 3.1.7 on 2021-03-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The url to scrape', max_length=4096, verbose_name='url')),
                ('regex', models.CharField(blank=True, help_text='An optional regex to grab the json table', max_length=256, verbose_name='regex')),
                ('date_key', models.CharField(help_text='The key must yield a date', max_length=32, verbose_name='Date Key')),
                ('price_key', models.CharField(help_text='The key must yield a price', max_length=32, verbose_name='Price Key')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security', to='investing.security', verbose_name='security')),
            ],
            options={
                'verbose_name': 'scraper',
                'verbose_name_plural': 'scrapers',
                'ordering': ['security__name'],
            },
        ),
    ]
