# Generated by Django 3.1.7 on 2021-03-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short descriptive name for the Scraper', max_length=256, verbose_name='naam')),
                ('url', models.URLField(help_text='The url to scrape', max_length=4096, verbose_name='url')),
                ('regex', models.CharField(blank=True, help_text='An optional regex to grab a specific part of the webpage', max_length=256, verbose_name='regex')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueScraper',
            fields=[
                ('scraper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapers.scraper')),
                ('key_path', models.CharField(help_text='The path must yield an array with keys', max_length=32, verbose_name='Key Path')),
                ('value_path', models.CharField(help_text='The path must yield an array with values', max_length=32, verbose_name='Value Path')),
            ],
            options={
                'verbose_name': 'keyvalue scraper',
                'verbose_name_plural': 'keyvalue scrapers',
                'ordering': ['url'],
            },
            bases=('scrapers.scraper',),
        ),
    ]
