# Generated by Django 3.1.7 on 2021-03-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_auto_20210316_1127'),
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='scraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scrapers.keyvaluescraper', verbose_name='scraper'),
        ),
    ]
