# Generated by Django 3.1.7 on 2021-03-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(help_text='A short descriptive name for the Security (max_length )', max_length=256, verbose_name='naam')),
                ('isin', models.CharField(help_text='International Securities Identification Number', max_length=12, unique=True, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'security',
                'verbose_name_plural': 'securities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='price')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.security', verbose_name='security')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'ordering': ['date'],
                'get_latest_by': '-date',
            },
        ),
    ]
