# Generated by Django 3.1.7 on 2021-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(help_text='A short descriptive name for the Scraper', max_length=256, verbose_name='naam')),
                ('url', models.URLField(help_text='The url to scrape', max_length=4096, verbose_name='price')),
            ],
            options={
                'verbose_name': 'scraper',
                'verbose_name_plural': 'scrapers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'get_latest_by': 'date', 'ordering': ['date'], 'verbose_name': 'quote', 'verbose_name_plural': 'quotes'},
        ),
    ]
