# Generated by Django 3.1.7 on 2021-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210312_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='regex',
            field=models.CharField(blank=True, help_text='An optional regex to grab the json table', max_length=256, verbose_name='regex'),
        ),
    ]
