# Generated by Django 3.1.7 on 2021-03-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_scraper_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='security',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='security', to='quotes.security', verbose_name='security'),
            preserve_default=False,
        ),
    ]
