# Generated by Django 3.1.7 on 2021-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_scraper_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='date_key',
            field=models.CharField(default='x', help_text='The key must yield a date', max_length=32, verbose_name='Date Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraper',
            name='price_key',
            field=models.CharField(default='y', help_text='The key must yield a price', max_length=32, verbose_name='Price Key'),
            preserve_default=False,
        ),
    ]
