name: Build and Test

# Triggers
on:
  # Opening a pull request to main branch will be a trigger
  pull_request:
    branches:
      - main

# Job definition
jobs:
  build-and-test:
    runs-on: ubuntu-latest # os for running the job
    env:
      working-directory: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup python environment # setting python environment to 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Python version
        run: python --version

      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: ${{env.working-directory}}

      - name: Check Code Style
        run: pycodestyle --statistics --max-line-length=120 .
        working-directory: ${{env.working-directory}}

      - name: Run Migrations
        run: python manage.py migrate
        working-directory: ${{env.working-directory}}

      - name: Run Tests
        run: coverage run
        working-directory: ${{env.working-directory}}

      - name: Coverage Report
        run: coverage report
        working-directory: ${{env.working-directory}}
